// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static Appli.Controllers.AccountController Account = new Appli.Controllers.T4MVC_AccountController();
    public static Appli.Controllers.CustomersController Customers = new Appli.Controllers.T4MVC_CustomersController();
    public static Appli.Controllers.HomeController Home = new Appli.Controllers.T4MVC_HomeController();
    public static Appli.Controllers.ManageController Manage = new Appli.Controllers.T4MVC_ManageController();
    public static Appli.Controllers.MoviesController Movies = new Appli.Controllers.T4MVC_MoviesController();
    public static Appli.Controllers.RentalsController Rentals = new Appli.Controllers.T4MVC_RentalsController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bloodhound_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bloodhound.min.js") ? Url("bloodhound.min.js") : Url("bloodhound.js");
        public static readonly string bloodhound_min_js = Url("bloodhound.min.js");
        public static readonly string bootbox_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootbox.min.js") ? Url("bootbox.min.js") : Url("bootbox.js");
        public static readonly string bootbox_min_js = Url("bootbox.min.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class DataTables {
            public const string UrlPath = "~/Scripts/DataTables";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string autoFill_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autoFill.bootstrap.min.js") ? Url("autoFill.bootstrap.min.js") : Url("autoFill.bootstrap.js");
            public static readonly string autoFill_bootstrap_min_js = Url("autoFill.bootstrap.min.js");
            public static readonly string autoFill_foundation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autoFill.foundation.min.js") ? Url("autoFill.foundation.min.js") : Url("autoFill.foundation.js");
            public static readonly string autoFill_foundation_min_js = Url("autoFill.foundation.min.js");
            public static readonly string autoFill_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autoFill.jqueryui.min.js") ? Url("autoFill.jqueryui.min.js") : Url("autoFill.jqueryui.js");
            public static readonly string autoFill_jqueryui_min_js = Url("autoFill.jqueryui.min.js");
            public static readonly string buttons_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.bootstrap.min.js") ? Url("buttons.bootstrap.min.js") : Url("buttons.bootstrap.js");
            public static readonly string buttons_bootstrap_min_js = Url("buttons.bootstrap.min.js");
            public static readonly string buttons_bootstrap4_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.bootstrap4.min.js") ? Url("buttons.bootstrap4.min.js") : Url("buttons.bootstrap4.js");
            public static readonly string buttons_bootstrap4_min_js = Url("buttons.bootstrap4.min.js");
            public static readonly string buttons_colVis_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.colVis.min.js") ? Url("buttons.colVis.min.js") : Url("buttons.colVis.js");
            public static readonly string buttons_colVis_min_js = Url("buttons.colVis.min.js");
            public static readonly string buttons_flash_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.flash.min.js") ? Url("buttons.flash.min.js") : Url("buttons.flash.js");
            public static readonly string buttons_flash_min_js = Url("buttons.flash.min.js");
            public static readonly string buttons_foundation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.foundation.min.js") ? Url("buttons.foundation.min.js") : Url("buttons.foundation.js");
            public static readonly string buttons_foundation_min_js = Url("buttons.foundation.min.js");
            public static readonly string buttons_html5_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.html5.min.js") ? Url("buttons.html5.min.js") : Url("buttons.html5.js");
            public static readonly string buttons_html5_min_js = Url("buttons.html5.min.js");
            public static readonly string buttons_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.jqueryui.min.js") ? Url("buttons.jqueryui.min.js") : Url("buttons.jqueryui.js");
            public static readonly string buttons_jqueryui_min_js = Url("buttons.jqueryui.min.js");
            public static readonly string buttons_print_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.print.min.js") ? Url("buttons.print.min.js") : Url("buttons.print.js");
            public static readonly string buttons_print_min_js = Url("buttons.print.min.js");
            public static readonly string dataTables_autoFill_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.autoFill.min.js") ? Url("dataTables.autoFill.min.js") : Url("dataTables.autoFill.js");
            public static readonly string dataTables_autoFill_min_js = Url("dataTables.autoFill.min.js");
            public static readonly string dataTables_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.bootstrap.min.js") ? Url("dataTables.bootstrap.min.js") : Url("dataTables.bootstrap.js");
            public static readonly string dataTables_bootstrap_min_js = Url("dataTables.bootstrap.min.js");
            public static readonly string dataTables_bootstrap4_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.bootstrap4.min.js") ? Url("dataTables.bootstrap4.min.js") : Url("dataTables.bootstrap4.js");
            public static readonly string dataTables_bootstrap4_min_js = Url("dataTables.bootstrap4.min.js");
            public static readonly string dataTables_buttons_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.buttons.min.js") ? Url("dataTables.buttons.min.js") : Url("dataTables.buttons.js");
            public static readonly string dataTables_buttons_min_js = Url("dataTables.buttons.min.js");
            public static readonly string dataTables_colReorder_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.colReorder.min.js") ? Url("dataTables.colReorder.min.js") : Url("dataTables.colReorder.js");
            public static readonly string dataTables_colReorder_min_js = Url("dataTables.colReorder.min.js");
            public static readonly string dataTables_fixedColumns_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.fixedColumns.min.js") ? Url("dataTables.fixedColumns.min.js") : Url("dataTables.fixedColumns.js");
            public static readonly string dataTables_fixedColumns_min_js = Url("dataTables.fixedColumns.min.js");
            public static readonly string dataTables_fixedHeader_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.fixedHeader.min.js") ? Url("dataTables.fixedHeader.min.js") : Url("dataTables.fixedHeader.js");
            public static readonly string dataTables_fixedHeader_min_js = Url("dataTables.fixedHeader.min.js");
            public static readonly string dataTables_foundation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.foundation.min.js") ? Url("dataTables.foundation.min.js") : Url("dataTables.foundation.js");
            public static readonly string dataTables_foundation_min_js = Url("dataTables.foundation.min.js");
            public static readonly string dataTables_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.jqueryui.min.js") ? Url("dataTables.jqueryui.min.js") : Url("dataTables.jqueryui.js");
            public static readonly string dataTables_jqueryui_min_js = Url("dataTables.jqueryui.min.js");
            public static readonly string dataTables_keyTable_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.keyTable.min.js") ? Url("dataTables.keyTable.min.js") : Url("dataTables.keyTable.js");
            public static readonly string dataTables_keyTable_min_js = Url("dataTables.keyTable.min.js");
            public static readonly string dataTables_material_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.material.min.js") ? Url("dataTables.material.min.js") : Url("dataTables.material.js");
            public static readonly string dataTables_material_min_js = Url("dataTables.material.min.js");
            public static readonly string dataTables_responsive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.responsive.min.js") ? Url("dataTables.responsive.min.js") : Url("dataTables.responsive.js");
            public static readonly string dataTables_responsive_min_js = Url("dataTables.responsive.min.js");
            public static readonly string dataTables_rowReorder_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.rowReorder.min.js") ? Url("dataTables.rowReorder.min.js") : Url("dataTables.rowReorder.js");
            public static readonly string dataTables_rowReorder_min_js = Url("dataTables.rowReorder.min.js");
            public static readonly string dataTables_scroller_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.scroller.min.js") ? Url("dataTables.scroller.min.js") : Url("dataTables.scroller.js");
            public static readonly string dataTables_scroller_min_js = Url("dataTables.scroller.min.js");
            public static readonly string dataTables_select_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.select.min.js") ? Url("dataTables.select.min.js") : Url("dataTables.select.js");
            public static readonly string dataTables_select_min_js = Url("dataTables.select.min.js");
            public static readonly string dataTables_semanticui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.semanticui.min.js") ? Url("dataTables.semanticui.min.js") : Url("dataTables.semanticui.js");
            public static readonly string dataTables_semanticui_min_js = Url("dataTables.semanticui.min.js");
            public static readonly string dataTables_uikit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.uikit.min.js") ? Url("dataTables.uikit.min.js") : Url("dataTables.uikit.js");
            public static readonly string dataTables_uikit_min_js = Url("dataTables.uikit.min.js");
            public static readonly string jquery_dataTables_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.dataTables.min.js") ? Url("jquery.dataTables.min.js") : Url("jquery.dataTables.js");
            public static readonly string jquery_dataTables_min_js = Url("jquery.dataTables.min.js");
            public static readonly string responsive_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.bootstrap.min.js") ? Url("responsive.bootstrap.min.js") : Url("responsive.bootstrap.js");
            public static readonly string responsive_bootstrap_min_js = Url("responsive.bootstrap.min.js");
            public static readonly string responsive_foundation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.foundation.min.js") ? Url("responsive.foundation.min.js") : Url("responsive.foundation.js");
            public static readonly string responsive_foundation_min_js = Url("responsive.foundation.min.js");
            public static readonly string responsive_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.jqueryui.min.js") ? Url("responsive.jqueryui.min.js") : Url("responsive.jqueryui.js");
            public static readonly string responsive_jqueryui_min_js = Url("responsive.jqueryui.min.js");
        }
    
        public static readonly string jquery_3_3_1_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.3.1.intellisense.min.js") ? Url("jquery-3.3.1.intellisense.min.js") : Url("jquery-3.3.1.intellisense.js");
        public static readonly string jquery_3_3_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.3.1.min.js") ? Url("jquery-3.3.1.min.js") : Url("jquery-3.3.1.js");
        public static readonly string jquery_3_3_1_min_js = Url("jquery-3.3.1.min.js");
        public static readonly string jquery_3_3_1_min_map = Url("jquery-3.3.1.min.map");
        public static readonly string jquery_3_3_1_slim_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-3.3.1.slim.min.js") ? Url("jquery-3.3.1.slim.min.js") : Url("jquery-3.3.1.slim.js");
        public static readonly string jquery_3_3_1_slim_min_js = Url("jquery-3.3.1.slim.min.js");
        public static readonly string jquery_3_3_1_slim_min_map = Url("jquery-3.3.1.slim.min.map");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        public static readonly string typeahead_bundle_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/typeahead.bundle.min.js") ? Url("typeahead.bundle.min.js") : Url("typeahead.bundle.js");
        public static readonly string typeahead_bundle_min_js = Url("typeahead.bundle.min.js");
        public static readonly string typeahead_jquery_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/typeahead.jquery.min.js") ? Url("typeahead.jquery.min.js") : Url("typeahead.jquery.js");
        public static readonly string typeahead_jquery_min_js = Url("typeahead.jquery.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bootstrap_darkly_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-darkly.min.css") ? Url("bootstrap-darkly.min.css") : Url("bootstrap-darkly.css");
        public static readonly string bootstrap_lumen_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-lumen.min.css") ? Url("bootstrap-lumen.min.css") : Url("bootstrap-lumen.css");
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_theme_min_css_map = Url("bootstrap-theme.min.css.map");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string bootstrap_min_css_map = Url("bootstrap.min.css.map");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class DataTables {
            public const string UrlPath = "~/Content/DataTables";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                public const string UrlPath = "~/Content/DataTables/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string autoFill_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autoFill.bootstrap.min.css") ? Url("autoFill.bootstrap.min.css") : Url("autoFill.bootstrap.css");
                public static readonly string autoFill_bootstrap_min_css = Url("autoFill.bootstrap.min.css");
                public static readonly string autoFill_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autoFill.dataTables.min.css") ? Url("autoFill.dataTables.min.css") : Url("autoFill.dataTables.css");
                public static readonly string autoFill_dataTables_min_css = Url("autoFill.dataTables.min.css");
                public static readonly string autoFill_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autoFill.foundation.min.css") ? Url("autoFill.foundation.min.css") : Url("autoFill.foundation.css");
                public static readonly string autoFill_foundation_min_css = Url("autoFill.foundation.min.css");
                public static readonly string autoFill_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/autoFill.jqueryui.min.css") ? Url("autoFill.jqueryui.min.css") : Url("autoFill.jqueryui.css");
                public static readonly string autoFill_jqueryui_min_css = Url("autoFill.jqueryui.min.css");
                public static readonly string buttons_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.bootstrap.min.css") ? Url("buttons.bootstrap.min.css") : Url("buttons.bootstrap.css");
                public static readonly string buttons_bootstrap_min_css = Url("buttons.bootstrap.min.css");
                public static readonly string buttons_bootstrap4_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.bootstrap4.min.css") ? Url("buttons.bootstrap4.min.css") : Url("buttons.bootstrap4.css");
                public static readonly string buttons_bootstrap4_min_css = Url("buttons.bootstrap4.min.css");
                public static readonly string buttons_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.dataTables.min.css") ? Url("buttons.dataTables.min.css") : Url("buttons.dataTables.css");
                public static readonly string buttons_dataTables_min_css = Url("buttons.dataTables.min.css");
                public static readonly string buttons_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.foundation.min.css") ? Url("buttons.foundation.min.css") : Url("buttons.foundation.css");
                public static readonly string buttons_foundation_min_css = Url("buttons.foundation.min.css");
                public static readonly string buttons_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/buttons.jqueryui.min.css") ? Url("buttons.jqueryui.min.css") : Url("buttons.jqueryui.css");
                public static readonly string buttons_jqueryui_min_css = Url("buttons.jqueryui.min.css");
                public static readonly string colReorder_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/colReorder.bootstrap.min.css") ? Url("colReorder.bootstrap.min.css") : Url("colReorder.bootstrap.css");
                public static readonly string colReorder_bootstrap_min_css = Url("colReorder.bootstrap.min.css");
                public static readonly string colReorder_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/colReorder.dataTables.min.css") ? Url("colReorder.dataTables.min.css") : Url("colReorder.dataTables.css");
                public static readonly string colReorder_dataTables_min_css = Url("colReorder.dataTables.min.css");
                public static readonly string colReorder_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/colReorder.foundation.min.css") ? Url("colReorder.foundation.min.css") : Url("colReorder.foundation.css");
                public static readonly string colReorder_foundation_min_css = Url("colReorder.foundation.min.css");
                public static readonly string colReorder_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/colReorder.jqueryui.min.css") ? Url("colReorder.jqueryui.min.css") : Url("colReorder.jqueryui.css");
                public static readonly string colReorder_jqueryui_min_css = Url("colReorder.jqueryui.min.css");
                public static readonly string common_scss = Url("common.scss");
                public static readonly string dataTables_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.bootstrap.min.css") ? Url("dataTables.bootstrap.min.css") : Url("dataTables.bootstrap.css");
                public static readonly string dataTables_bootstrap_min_css = Url("dataTables.bootstrap.min.css");
                public static readonly string dataTables_bootstrap4_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.bootstrap4.min.css") ? Url("dataTables.bootstrap4.min.css") : Url("dataTables.bootstrap4.css");
                public static readonly string dataTables_bootstrap4_min_css = Url("dataTables.bootstrap4.min.css");
                public static readonly string dataTables_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.foundation.min.css") ? Url("dataTables.foundation.min.css") : Url("dataTables.foundation.css");
                public static readonly string dataTables_foundation_min_css = Url("dataTables.foundation.min.css");
                public static readonly string dataTables_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.jqueryui.min.css") ? Url("dataTables.jqueryui.min.css") : Url("dataTables.jqueryui.css");
                public static readonly string dataTables_jqueryui_min_css = Url("dataTables.jqueryui.min.css");
                public static readonly string dataTables_material_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.material.min.css") ? Url("dataTables.material.min.css") : Url("dataTables.material.css");
                public static readonly string dataTables_material_min_css = Url("dataTables.material.min.css");
                public static readonly string dataTables_semanticui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.semanticui.min.css") ? Url("dataTables.semanticui.min.css") : Url("dataTables.semanticui.css");
                public static readonly string dataTables_semanticui_min_css = Url("dataTables.semanticui.min.css");
                public static readonly string dataTables_uikit_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/dataTables.uikit.min.css") ? Url("dataTables.uikit.min.css") : Url("dataTables.uikit.css");
                public static readonly string dataTables_uikit_min_css = Url("dataTables.uikit.min.css");
                public static readonly string fixedColumns_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedColumns.bootstrap.min.css") ? Url("fixedColumns.bootstrap.min.css") : Url("fixedColumns.bootstrap.css");
                public static readonly string fixedColumns_bootstrap_min_css = Url("fixedColumns.bootstrap.min.css");
                public static readonly string fixedColumns_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedColumns.dataTables.min.css") ? Url("fixedColumns.dataTables.min.css") : Url("fixedColumns.dataTables.css");
                public static readonly string fixedColumns_dataTables_min_css = Url("fixedColumns.dataTables.min.css");
                public static readonly string fixedColumns_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedColumns.foundation.min.css") ? Url("fixedColumns.foundation.min.css") : Url("fixedColumns.foundation.css");
                public static readonly string fixedColumns_foundation_min_css = Url("fixedColumns.foundation.min.css");
                public static readonly string fixedColumns_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedColumns.jqueryui.min.css") ? Url("fixedColumns.jqueryui.min.css") : Url("fixedColumns.jqueryui.css");
                public static readonly string fixedColumns_jqueryui_min_css = Url("fixedColumns.jqueryui.min.css");
                public static readonly string fixedHeader_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedHeader.bootstrap.min.css") ? Url("fixedHeader.bootstrap.min.css") : Url("fixedHeader.bootstrap.css");
                public static readonly string fixedHeader_bootstrap_min_css = Url("fixedHeader.bootstrap.min.css");
                public static readonly string fixedHeader_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedHeader.dataTables.min.css") ? Url("fixedHeader.dataTables.min.css") : Url("fixedHeader.dataTables.css");
                public static readonly string fixedHeader_dataTables_min_css = Url("fixedHeader.dataTables.min.css");
                public static readonly string fixedHeader_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedHeader.foundation.min.css") ? Url("fixedHeader.foundation.min.css") : Url("fixedHeader.foundation.css");
                public static readonly string fixedHeader_foundation_min_css = Url("fixedHeader.foundation.min.css");
                public static readonly string fixedHeader_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fixedHeader.jqueryui.min.css") ? Url("fixedHeader.jqueryui.min.css") : Url("fixedHeader.jqueryui.css");
                public static readonly string fixedHeader_jqueryui_min_css = Url("fixedHeader.jqueryui.min.css");
                public static readonly string jquery_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.dataTables.min.css") ? Url("jquery.dataTables.min.css") : Url("jquery.dataTables.css");
                public static readonly string jquery_dataTables_min_css = Url("jquery.dataTables.min.css");
                public static readonly string jquery_dataTables_themeroller_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.dataTables_themeroller.min.css") ? Url("jquery.dataTables_themeroller.min.css") : Url("jquery.dataTables_themeroller.css");
                public static readonly string keyTable_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/keyTable.bootstrap.min.css") ? Url("keyTable.bootstrap.min.css") : Url("keyTable.bootstrap.css");
                public static readonly string keyTable_bootstrap_min_css = Url("keyTable.bootstrap.min.css");
                public static readonly string keyTable_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/keyTable.dataTables.min.css") ? Url("keyTable.dataTables.min.css") : Url("keyTable.dataTables.css");
                public static readonly string keyTable_dataTables_min_css = Url("keyTable.dataTables.min.css");
                public static readonly string keyTable_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/keyTable.foundation.min.css") ? Url("keyTable.foundation.min.css") : Url("keyTable.foundation.css");
                public static readonly string keyTable_foundation_min_css = Url("keyTable.foundation.min.css");
                public static readonly string keyTable_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/keyTable.jqueryui.min.css") ? Url("keyTable.jqueryui.min.css") : Url("keyTable.jqueryui.css");
                public static readonly string keyTable_jqueryui_min_css = Url("keyTable.jqueryui.min.css");
                public static readonly string mixins_scss = Url("mixins.scss");
                public static readonly string responsive_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.bootstrap.min.css") ? Url("responsive.bootstrap.min.css") : Url("responsive.bootstrap.css");
                public static readonly string responsive_bootstrap_min_css = Url("responsive.bootstrap.min.css");
                public static readonly string responsive_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.dataTables.min.css") ? Url("responsive.dataTables.min.css") : Url("responsive.dataTables.css");
                public static readonly string responsive_dataTables_min_css = Url("responsive.dataTables.min.css");
                public static readonly string responsive_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.foundation.min.css") ? Url("responsive.foundation.min.css") : Url("responsive.foundation.css");
                public static readonly string responsive_foundation_min_css = Url("responsive.foundation.min.css");
                public static readonly string responsive_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.jqueryui.min.css") ? Url("responsive.jqueryui.min.css") : Url("responsive.jqueryui.css");
                public static readonly string responsive_jqueryui_min_css = Url("responsive.jqueryui.min.css");
                public static readonly string rowReorder_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/rowReorder.bootstrap.min.css") ? Url("rowReorder.bootstrap.min.css") : Url("rowReorder.bootstrap.css");
                public static readonly string rowReorder_bootstrap_min_css = Url("rowReorder.bootstrap.min.css");
                public static readonly string rowReorder_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/rowReorder.dataTables.min.css") ? Url("rowReorder.dataTables.min.css") : Url("rowReorder.dataTables.css");
                public static readonly string rowReorder_dataTables_min_css = Url("rowReorder.dataTables.min.css");
                public static readonly string rowReorder_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/rowReorder.foundation.min.css") ? Url("rowReorder.foundation.min.css") : Url("rowReorder.foundation.css");
                public static readonly string rowReorder_foundation_min_css = Url("rowReorder.foundation.min.css");
                public static readonly string rowReorder_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/rowReorder.jqueryui.min.css") ? Url("rowReorder.jqueryui.min.css") : Url("rowReorder.jqueryui.css");
                public static readonly string rowReorder_jqueryui_min_css = Url("rowReorder.jqueryui.min.css");
                public static readonly string scroller_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/scroller.bootstrap.min.css") ? Url("scroller.bootstrap.min.css") : Url("scroller.bootstrap.css");
                public static readonly string scroller_bootstrap_min_css = Url("scroller.bootstrap.min.css");
                public static readonly string scroller_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/scroller.dataTables.min.css") ? Url("scroller.dataTables.min.css") : Url("scroller.dataTables.css");
                public static readonly string scroller_dataTables_min_css = Url("scroller.dataTables.min.css");
                public static readonly string scroller_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/scroller.foundation.min.css") ? Url("scroller.foundation.min.css") : Url("scroller.foundation.css");
                public static readonly string scroller_foundation_min_css = Url("scroller.foundation.min.css");
                public static readonly string scroller_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/scroller.jqueryui.min.css") ? Url("scroller.jqueryui.min.css") : Url("scroller.jqueryui.css");
                public static readonly string scroller_jqueryui_min_css = Url("scroller.jqueryui.min.css");
                public static readonly string select_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/select.bootstrap.min.css") ? Url("select.bootstrap.min.css") : Url("select.bootstrap.css");
                public static readonly string select_bootstrap_min_css = Url("select.bootstrap.min.css");
                public static readonly string select_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/select.dataTables.min.css") ? Url("select.dataTables.min.css") : Url("select.dataTables.css");
                public static readonly string select_dataTables_min_css = Url("select.dataTables.min.css");
                public static readonly string select_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/select.foundation.min.css") ? Url("select.foundation.min.css") : Url("select.foundation.css");
                public static readonly string select_foundation_min_css = Url("select.foundation.min.css");
                public static readonly string select_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/select.jqueryui.min.css") ? Url("select.jqueryui.min.css") : Url("select.jqueryui.css");
                public static readonly string select_jqueryui_min_css = Url("select.jqueryui.min.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class images {
                public const string UrlPath = "~/Content/DataTables/images";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string details_close_png = Url("details_close.png");
                public static readonly string details_open_png = Url("details_open.png");
                public static readonly string sort_asc_png = Url("sort_asc.png");
                public static readonly string sort_asc_disabled_png = Url("sort_asc_disabled.png");
                public static readonly string sort_both_png = Url("sort_both.png");
                public static readonly string sort_desc_png = Url("sort_desc.png");
                public static readonly string sort_desc_disabled_png = Url("sort_desc_disabled.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class swf {
                public const string UrlPath = "~/Content/DataTables/swf";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string flashExport_swf = Url("flashExport.swf");
            }
        
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        public static readonly string typeahead_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/typeahead.min.css") ? Url("typeahead.min.css") : Url("typeahead.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class DataTables 
            {
                public static class Assets
                {
                    public static readonly string autoFill_bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/autoFill.bootstrap.js"); 
                    public static readonly string autoFill_bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/autoFill.bootstrap.min.js"); 
                    public static readonly string autoFill_foundation_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/autoFill.foundation.js"); 
                    public static readonly string autoFill_foundation_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/autoFill.foundation.min.js"); 
                    public static readonly string autoFill_jqueryui_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/autoFill.jqueryui.js"); 
                    public static readonly string autoFill_jqueryui_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/autoFill.jqueryui.min.js"); 
                    public static readonly string buttons_bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.bootstrap.js"); 
                    public static readonly string buttons_bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.bootstrap.min.js"); 
                    public static readonly string buttons_bootstrap4_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.bootstrap4.js"); 
                    public static readonly string buttons_bootstrap4_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.bootstrap4.min.js"); 
                    public static readonly string buttons_colVis_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.colVis.js"); 
                    public static readonly string buttons_colVis_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.colVis.min.js"); 
                    public static readonly string buttons_flash_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.flash.js"); 
                    public static readonly string buttons_flash_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.flash.min.js"); 
                    public static readonly string buttons_foundation_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.foundation.js"); 
                    public static readonly string buttons_foundation_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.foundation.min.js"); 
                    public static readonly string buttons_html5_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.html5.js"); 
                    public static readonly string buttons_html5_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.html5.min.js"); 
                    public static readonly string buttons_jqueryui_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.jqueryui.js"); 
                    public static readonly string buttons_jqueryui_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.jqueryui.min.js"); 
                    public static readonly string buttons_print_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.print.js"); 
                    public static readonly string buttons_print_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/buttons.print.min.js"); 
                    public static readonly string dataTables_autoFill_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.autoFill.js"); 
                    public static readonly string dataTables_autoFill_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.autoFill.min.js"); 
                    public static readonly string dataTables_bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.bootstrap.js"); 
                    public static readonly string dataTables_bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.bootstrap.min.js"); 
                    public static readonly string dataTables_bootstrap4_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.bootstrap4.js"); 
                    public static readonly string dataTables_bootstrap4_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.bootstrap4.min.js"); 
                    public static readonly string dataTables_buttons_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.buttons.js"); 
                    public static readonly string dataTables_buttons_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.buttons.min.js"); 
                    public static readonly string dataTables_colReorder_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.colReorder.js"); 
                    public static readonly string dataTables_colReorder_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.colReorder.min.js"); 
                    public static readonly string dataTables_fixedColumns_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.fixedColumns.js"); 
                    public static readonly string dataTables_fixedColumns_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.fixedColumns.min.js"); 
                    public static readonly string dataTables_fixedHeader_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.fixedHeader.js"); 
                    public static readonly string dataTables_fixedHeader_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.fixedHeader.min.js"); 
                    public static readonly string dataTables_foundation_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.foundation.js"); 
                    public static readonly string dataTables_foundation_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.foundation.min.js"); 
                    public static readonly string dataTables_jqueryui_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.jqueryui.js"); 
                    public static readonly string dataTables_jqueryui_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.jqueryui.min.js"); 
                    public static readonly string dataTables_keyTable_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.keyTable.js"); 
                    public static readonly string dataTables_keyTable_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.keyTable.min.js"); 
                    public static readonly string dataTables_material_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.material.js"); 
                    public static readonly string dataTables_material_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.material.min.js"); 
                    public static readonly string dataTables_responsive_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.responsive.js"); 
                    public static readonly string dataTables_responsive_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.responsive.min.js"); 
                    public static readonly string dataTables_rowReorder_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.rowReorder.js"); 
                    public static readonly string dataTables_rowReorder_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.rowReorder.min.js"); 
                    public static readonly string dataTables_scroller_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.scroller.js"); 
                    public static readonly string dataTables_scroller_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.scroller.min.js"); 
                    public static readonly string dataTables_select_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.select.js"); 
                    public static readonly string dataTables_select_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.select.min.js"); 
                    public static readonly string dataTables_semanticui_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.semanticui.js"); 
                    public static readonly string dataTables_semanticui_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.semanticui.min.js"); 
                    public static readonly string dataTables_uikit_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.uikit.js"); 
                    public static readonly string dataTables_uikit_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/dataTables.uikit.min.js"); 
                    public static readonly string jquery_dataTables_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/jquery.dataTables.js"); 
                    public static readonly string jquery_dataTables_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/jquery.dataTables.min.js"); 
                    public static readonly string responsive_bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/responsive.bootstrap.js"); 
                    public static readonly string responsive_bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/responsive.bootstrap.min.js"); 
                    public static readonly string responsive_foundation_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/responsive.foundation.js"); 
                    public static readonly string responsive_foundation_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/responsive.foundation.min.js"); 
                    public static readonly string responsive_jqueryui_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/responsive.jqueryui.js"); 
                    public static readonly string responsive_jqueryui_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/DataTables/responsive.jqueryui.min.js"); 
                }
            }
            public static class Assets
            {
                public static readonly string bloodhound_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bloodhound.js"); 
                public static readonly string bloodhound_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bloodhound.min.js"); 
                public static readonly string bootbox_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootbox.js"); 
                public static readonly string bootbox_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootbox.min.js"); 
                public static readonly string bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.js"); 
                public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.min.js"); 
                public static readonly string jquery_3_3_1_intellisense_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-3.3.1.intellisense.js"); 
                public static readonly string jquery_3_3_1_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-3.3.1.js"); 
                public static readonly string jquery_3_3_1_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-3.3.1.min.js"); 
                public static readonly string jquery_3_3_1_slim_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-3.3.1.slim.js"); 
                public static readonly string jquery_3_3_1_slim_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-3.3.1.slim.min.js"); 
                public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.js"); 
                public static readonly string jquery_validate_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.min.js"); 
                public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.js"); 
                public static readonly string jquery_validate_unobtrusive_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.min.js"); 
                public static readonly string modernizr_2_8_3_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/modernizr-2.8.3.js"); 
                public static readonly string typeahead_bundle_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/typeahead.bundle.js"); 
                public static readonly string typeahead_bundle_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/typeahead.bundle.min.js"); 
                public static readonly string typeahead_jquery_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/typeahead.jquery.js"); 
                public static readonly string typeahead_jquery_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/typeahead.jquery.min.js"); 
            }
        }
        public static partial class Content 
        {
            public static partial class DataTables 
            {
                public static partial class css 
                {
                    public static class Assets
                    {
                        public static readonly string autoFill_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.bootstrap.css");
                        public static readonly string autoFill_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.bootstrap.min.css");
                        public static readonly string autoFill_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.dataTables.css");
                        public static readonly string autoFill_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.dataTables.min.css");
                        public static readonly string autoFill_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.foundation.css");
                        public static readonly string autoFill_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.foundation.min.css");
                        public static readonly string autoFill_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.jqueryui.css");
                        public static readonly string autoFill_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/autoFill.jqueryui.min.css");
                        public static readonly string buttons_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.bootstrap.css");
                        public static readonly string buttons_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.bootstrap.min.css");
                        public static readonly string buttons_bootstrap4_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.bootstrap4.css");
                        public static readonly string buttons_bootstrap4_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.bootstrap4.min.css");
                        public static readonly string buttons_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.dataTables.css");
                        public static readonly string buttons_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.dataTables.min.css");
                        public static readonly string buttons_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.foundation.css");
                        public static readonly string buttons_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.foundation.min.css");
                        public static readonly string buttons_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.jqueryui.css");
                        public static readonly string buttons_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/buttons.jqueryui.min.css");
                        public static readonly string colReorder_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.bootstrap.css");
                        public static readonly string colReorder_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.bootstrap.min.css");
                        public static readonly string colReorder_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.dataTables.css");
                        public static readonly string colReorder_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.dataTables.min.css");
                        public static readonly string colReorder_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.foundation.css");
                        public static readonly string colReorder_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.foundation.min.css");
                        public static readonly string colReorder_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.jqueryui.css");
                        public static readonly string colReorder_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/colReorder.jqueryui.min.css");
                        public static readonly string dataTables_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.bootstrap.css");
                        public static readonly string dataTables_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.bootstrap.min.css");
                        public static readonly string dataTables_bootstrap4_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.bootstrap4.css");
                        public static readonly string dataTables_bootstrap4_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.bootstrap4.min.css");
                        public static readonly string dataTables_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.foundation.css");
                        public static readonly string dataTables_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.foundation.min.css");
                        public static readonly string dataTables_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.jqueryui.css");
                        public static readonly string dataTables_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.jqueryui.min.css");
                        public static readonly string dataTables_material_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.material.css");
                        public static readonly string dataTables_material_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.material.min.css");
                        public static readonly string dataTables_semanticui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.semanticui.css");
                        public static readonly string dataTables_semanticui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.semanticui.min.css");
                        public static readonly string dataTables_uikit_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.uikit.css");
                        public static readonly string dataTables_uikit_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/dataTables.uikit.min.css");
                        public static readonly string fixedColumns_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.bootstrap.css");
                        public static readonly string fixedColumns_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.bootstrap.min.css");
                        public static readonly string fixedColumns_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.dataTables.css");
                        public static readonly string fixedColumns_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.dataTables.min.css");
                        public static readonly string fixedColumns_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.foundation.css");
                        public static readonly string fixedColumns_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.foundation.min.css");
                        public static readonly string fixedColumns_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.jqueryui.css");
                        public static readonly string fixedColumns_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedColumns.jqueryui.min.css");
                        public static readonly string fixedHeader_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.bootstrap.css");
                        public static readonly string fixedHeader_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.bootstrap.min.css");
                        public static readonly string fixedHeader_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.dataTables.css");
                        public static readonly string fixedHeader_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.dataTables.min.css");
                        public static readonly string fixedHeader_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.foundation.css");
                        public static readonly string fixedHeader_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.foundation.min.css");
                        public static readonly string fixedHeader_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.jqueryui.css");
                        public static readonly string fixedHeader_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/fixedHeader.jqueryui.min.css");
                        public static readonly string jquery_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/jquery.dataTables.css");
                        public static readonly string jquery_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/jquery.dataTables.min.css");
                        public static readonly string jquery_dataTables_themeroller_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/jquery.dataTables_themeroller.css");
                        public static readonly string keyTable_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.bootstrap.css");
                        public static readonly string keyTable_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.bootstrap.min.css");
                        public static readonly string keyTable_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.dataTables.css");
                        public static readonly string keyTable_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.dataTables.min.css");
                        public static readonly string keyTable_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.foundation.css");
                        public static readonly string keyTable_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.foundation.min.css");
                        public static readonly string keyTable_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.jqueryui.css");
                        public static readonly string keyTable_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/keyTable.jqueryui.min.css");
                        public static readonly string responsive_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.bootstrap.css");
                        public static readonly string responsive_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.bootstrap.min.css");
                        public static readonly string responsive_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.dataTables.css");
                        public static readonly string responsive_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.dataTables.min.css");
                        public static readonly string responsive_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.foundation.css");
                        public static readonly string responsive_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.foundation.min.css");
                        public static readonly string responsive_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.jqueryui.css");
                        public static readonly string responsive_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/responsive.jqueryui.min.css");
                        public static readonly string rowReorder_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.bootstrap.css");
                        public static readonly string rowReorder_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.bootstrap.min.css");
                        public static readonly string rowReorder_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.dataTables.css");
                        public static readonly string rowReorder_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.dataTables.min.css");
                        public static readonly string rowReorder_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.foundation.css");
                        public static readonly string rowReorder_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.foundation.min.css");
                        public static readonly string rowReorder_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.jqueryui.css");
                        public static readonly string rowReorder_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/rowReorder.jqueryui.min.css");
                        public static readonly string scroller_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.bootstrap.css");
                        public static readonly string scroller_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.bootstrap.min.css");
                        public static readonly string scroller_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.dataTables.css");
                        public static readonly string scroller_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.dataTables.min.css");
                        public static readonly string scroller_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.foundation.css");
                        public static readonly string scroller_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.foundation.min.css");
                        public static readonly string scroller_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.jqueryui.css");
                        public static readonly string scroller_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/scroller.jqueryui.min.css");
                        public static readonly string select_bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.bootstrap.css");
                        public static readonly string select_bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.bootstrap.min.css");
                        public static readonly string select_dataTables_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.dataTables.css");
                        public static readonly string select_dataTables_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.dataTables.min.css");
                        public static readonly string select_foundation_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.foundation.css");
                        public static readonly string select_foundation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.foundation.min.css");
                        public static readonly string select_jqueryui_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.jqueryui.css");
                        public static readonly string select_jqueryui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/DataTables/css/select.jqueryui.min.css");
                    }
                }
                public static partial class images 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class swf 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public static readonly string bootstrap_darkly_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-darkly.css");
                public static readonly string bootstrap_lumen_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-lumen.css");
                public static readonly string bootstrap_theme_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-theme.css");
                public static readonly string bootstrap_theme_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-theme.min.css");
                public static readonly string bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.css");
                public static readonly string bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.min.css");
                public static readonly string Site_css = T4MVCHelpers.ProcessAssetPath("~/Content/Site.css");
                public static readonly string typeahead_css = T4MVCHelpers.ProcessAssetPath("~/Content/typeahead.css");
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


